name: 'Release Please PR'

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.35.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
          fork: true
